import Image from "next/image";
import Banner from "@/public/banner.webp"
import Committee from "@/app/committees/components/Committee";
import CommitteeGuide from "@/app/committees/components/CommitteeGuide";
import {Metadata} from "next"

const committees: {name: string, description: string, guide?: string}[] = [
    {name: "Sağlık", guide: "https://drive.google.com/file/d/1ZyAEr5xCnoIEhH65oIMC7y40QBfrDq3N/view?usp=sharing", description: "Enfeksiyon hastalıkları dünya çapında salgınlara, mortalite ve morbiditede artışa sebep olabildiği gibi birçok kişide sakatlık ve işgücü kayıplarına da neden olmuştur. Bu hastalıklar aynı zamanda geri kalmış ve gelişmekte olan ülkelerde erken yaştaki ölümlerin önde gelen nedeni olarak da belirtilmektedir. Günümüzde mülteciler ve göçmenler dahil nüfusların iç ve uluslararası hareketleri, rastgele ve kontrolsüz şehirleşme, ekonomik gelişme ve arazilerin kullanış şekillerindeki değişiklikler ile oluşan ekolojik ve iklimsel değişiklikler hastalıkların yayılması için yeni fırsatlar yaratmaktadır. Çiçek aşısının bulunması ile çiçek hastalığı gibi bazı bulaşıcı hastalıkları yeryüzünden eradike edilmiştir, ancak AIDS, Ebola, Kırım Konga Kanamalı Ateşi / COVID-19 gibi yeni hastalıklar eradike edilen hastalıkların yerini hızla almıştır. The Economist tarafından yapılan analize göre, dünyada Covid-19'dan hayatını kaybedenlerin sayısının 14 milyon ile 23,5 milyon arasında olduğunu tahmin edilmekte, ülkemizde ise 102.174 kişinin ise yaşamını yitirdiği açıklanmıştır. Ülkemizdeki iç ve uluslararası hareketliliği, ekolojik ve iklimsel değişiklikleri göz önünde bulundurularak olası salgın hastalıklara karşı ne gibi önlemler alınabilir?"},
    {name: "İnsan Hakları", guide: "https://drive.google.com/file/d/1r_VW3wK_oX4uK9lPXbIsmOBYjtUcA3zy/view?usp=sharing", description: "Kamu güvenliği, vatandaşların, örgütlerin ve kurumların refahını tehditlere karşı korunmasını sağlayan bir hükûmet işlevidir. Kamu güvenliğini sağlayan başlıca kurumlar arasında polis,jandarma,askeriye ve itfaiye gibi kurumlar bulunmaktadır. Türkiye Cumhuriyeti'nde yaklaşık olarak 475.000 polis personeli,186.170 jandarma personeli, 895.000 askeri ve paralimiter personeli ve 33.578 itfaiye personeli bulunmaktadır. Bu personeller branşlaşma terfi sistemi, sivilleşme, aşırı merkezi yapı, siyasi müdahaleler,teşkilatlanmadaki yetersizlik gibi konulardan günden güne birçok sorunla karşılaşmaktadır. Bu sorunlar karşısında çözümlerin yetersiz kalmasından ve psikoloji bozulmalarından ötürü kamu güvenliği personelleri uygun olmayan çözüm yollarına hatta intihar girişimlerine başvurabilmektedirler. Ülkemizde bu sebeplerden dolayı son 10 yılda 569 jandarma ve 654 polis intihar girişiminde bulunmuştur ve bunların büyük bir çoğunluğu can kayıplarıyla sonuçlanmıştır. Bu bağlamda son yıllarda artan sorunlardan dolayı oluşan intihar girişimlerininin sayısını azaltmak amacıyla ne gibi önlemler alınabilir?"},
    {name: "Ekonomi", guide: "https://drive.google.com/file/d/1qkVPG1cDvJ46IX30QzGczQc5iadrmbex/view?usp=sharing", description: "Philips eğrisine göre işsizlik oranının düşük olduğu ekonomilerde enflasyon artar. İstihdam artışı ya da yüksek ücretler piyasada likidite bolluğuna neden olacağı için kısa dönemde enflasyonist etkiler oluşur. TÜİK verilerine göre 2023 Eylül ayi verilerine göre TÜFE veya yıllık enflasyon 2.59 puan artarak yüzde 61,53 düzeyinde seyretmiştir. Bununla beraber Ekim 2023 verilerine göre işsizlik oranı 2023 yılı Ağustos ayında yüzde 9,2 seviyesinde gerçekleşti. İstihdam edilenlerin sayısı 32 milyon 71 bin kişi, istihdam oranı ise yüzde 49 oldu. Dolayısıyla yüksek enflasyon ve yüksek işsizlik sorunlarıyla boğuşan ülkemizde fiyat istikrarını sağlamak ve iasthdam açığını kapatmak için neler yapılabilir?"},
    {name: "Eğitim", guide: "https://drive.google.com/file/d/1luyqc48V-eu2HsveqYnZ7iu302DiQMDw/view?usp=sharing", description: "Üniversite öğrencileri öğrenim hayatlarında temel ihtiyaçlarını karşılayacak barınma, beslenme, sağlıklı yaşama, güven içerisinde hayat sürme gibi bireysel ihtiyaçlarını karşılamarken ekonomik külfet içerisine girebilmekte ve büyük zorluklar yaşayabilmektedir. Öğrencilerin ders kitapları, ders araç gereçleri, kırtasiye alımı, barınma, ulaşım gibi ihtiyaçları aileleri zorlayabilmektedir. Yükseköğretim ücretsiz olsa bile kişinin yaşamını idame ettirmesi için ihtiyaçlarını da okurken karşılamak zorunda kalmakta ve bu da ekonomik yoksunluk içinde yer alan aileleri ve öğrencileri umutsuzluğa sürükleyebilmektedir. Zor ekonomik koşulların getirdiği sıkıntılar bir yana öğrenciler kendilerine ücretsiz sağlanan imkanlarla ilgili eksiklikler sebebiyle kyk yurtlarının içindeki eksiklikler, yurtların öğrenci sayısının bütününü kapsayıcı kapasiteye sahip olmaması gibi sorunlar yaşamaktadır. Son dönemlerde kalitesinde hızlı bir düşüş görülen üniversite öğrencilerinin yaşam koşullarını iyileştirmek adına ne gibi çalışmalar yürütülebilir?"},
    {name: "Çevre", guide: "https://drive.google.com/file/d/1Hsy5SVChTgKBaNWSm4MnKL-9xN2gJldw/view?usp=sharing", description: "1900-2014 yılları arasında Türkiye’de can ve mal kaybına neden olan en fazla deprem sayısının 5.5 - 5.9 magnitüd aralığında meydana geldiği, en çok can kaybı ve bina hasarına neden olan deprem büyüklüğünün sırasıyla 7.5 - 7.9 ve 7.0 - 7.4 aralığında olduğu, büyük can ve mal kaybına neden olan depremlerin en fazla 4 yılda bir meydana geldiği, Türkiye’deki 81 ilin 55’inde (%68) can kaybı ve/veya hasarın meydana geldiği, can kaybı ve hasarlı bina sayısı bakımından sayısal olarak en çok kayıp veren ilk beş bölge, büyükten küçüğe doğru; Doğu Anadolu, Marmara, Karadeniz, Ege, Akdeniz bölgeleri olarak sıralandığı belirlenmiştir. Aşırı göç alan kentlerde yaşanan kontrolsüz ve hızlı büyümeye bağlı olarak depreme karşı dayanıksız yapıların ve kentlerin oluşmasına neden olmuştur.  Halkın depreme karşı hazırlık ve duyarlılık konusunda yeteri kadar bilinçlenmemiş olması kayıpları arttırmaktadır.  Depremde hasar gören pek çok hasar alan yapıda; zemine göre bina yapmak yerine binaya göre zemin etüdünün hazırlandığı görülmektedir. Bu durum, can ve mal kayıplarının artmasında oldukça etkili olmuştur. Depremlerin etkisiyle altyapılar da büyük zararlar görmektedir. Türkiye’deki depremlerin yıkıcı özelliklerini azaltmak, deprem sonrası kullanılması gereken kaynakların ve altyapıların sağlamlığını sağlamak ve yıkıcı deprem riski bölgeleri içinde bulunan sanayi bölgelerinin zarar görüp ülke ekonomisini büyük ölçüde zarar vermesini önlemek için alınması gereken önlemlerin hızlanlandırılması ve geliştirilmesi, bu esnada  yapılanların denetiminin eksiksiz sağlanması için ne gibi uygulamalar yapılabilir?"},
    {name: "Tarım-Orman", guide: "https://drive.google.com/file/d/1J1qAW6DIcf50uIWbrDRWSLs9e9iJnAaQ/view?usp=sharing", description: "Türkiye'nin orman varlığı geçmişe kıyasla özellikle 2021 yılında büyük düşüş göstermiştir. Türkiye'deki orman varlığının azalması Türkiye coğrafyasında ekolojik dengenin bozulmasına ve bütün canlıların çeşitliliğini ve soyunu riske sokmaktadır. Aynı zamanda iklim krizine karşı etkisi azımsanamayacak derecede büyüktür ve büyük bir rol oynar. Ülkemizde ormanların azalmasındaki en büyük faktör yangındır. Bu yangınların yüzde 99'u antropojenik etkilerle oluşmuştur. Türkiye'deki orman yangını risklerini ve ormansızlaşmaya yol açan diğer diğer faktörlerin etkisini azaltmak ve orman arazilerinin ülke yüz ölçümüne kıyasla oranını güvenli ve süreğen bir şekilde attırmak için orman amenajman  stratejileri,   ülkemizin ekonomik, ekolojik ve sosyo-kültürel yapısına uygun olarak nasıl geliştirilebilir?"},
    {name: "Dışişleri", guide: "https://drive.google.com/file/d/1VxhdadI6eOuGjqQ_lRVcOUF1oM8VDryu/view?usp=sharing", description: "2014 yılında başlayan ve  24 Şubat 2022 tarihinde Donbas’a askeri harekatla büyüyen Ukrayna-Rusya savaşı ve İsrail ile Hamas arasında 1967 Altı Gün Savaşı'nda İsrail'in Filistin topraklarını işgal etmesiyle başlayıp uzun yıllarca devam etmiş İsrail-Filistin savaşı 7 Ekim 2023 tarihinde tekrardan ateşlenmiş, iki tane dünya basınında ses getiren büyük savaşın gerçekleştiği topraklar arasında bulunan Türkiye Cumhuriyeti’nin güvenlik hattında ve politikasında  tehditler oluşmuştur. Rusya-Ukrayna savaşında, Rusya'nın \"özel askeri operasyon\" diye tanımladığı harekâtın başladığı gün yaptığı açıklamalarla Ukrayna'nın toprak bütünlüğü ve siyasi birliğine saygı duyulması çağrısında bulunan ve Rusya'nın saldırısını reddettiğini ilan eden Türkiye, İsrail-Filistin savaşı doğrultusundaki Dışişleri Bakanı Fidan’ın açıklamasında, “Biz 7 Ekim’de ve müteakip süreçte, sivilleri hedef alan hiçbir eylemi tabii ki tasvip ediyoruz.” ifadesini kullanmış ve sivillerin korunmasınının öncelik olduğunu belli eden bir politika izlediğini dile getirmiştir. Türkiye Cumhuriyeti tarafından izlenilecek politikalar ile Türkiye’nin baş başa kaldığı bu tehditler sonucu oluşan kriz durumu nasıl Türkiye Cumhuriyeti lehine çevrilebilir?"},
    {name: "Turizm", guide: "https://drive.google.com/file/d/1UGzUxmUn1WIVygmiOwm0RoQb5obWZNIx/view?usp=sharing", description: "Birleşmiş Milletler Dünya Turizm Örgütü’ne (UNWTO) göre sürdürülebilir turizm şu anki ve gelecekteki bütün ekonomik sosyal ve çevresel etkilerinin tüm sorumluluğunu alabilen; ziyaretçilerin, endüstrinin, çevrenin ve ev sahibi toplulukların ihtiyaçlarını karşılayabilen turizmdir. Yine UNWTO’ya göre sürdürülebilir turizm, turizmde kritik bir etmen olan doğal kaynakları en optimal biçimde kullanarak doğayı korumalı, ev sahibi toplulukların sosyo-kültürel farklılıklarına saygı duyarak onların kültürlerine ve geleneklerine karşı koruyucu olmalı ve ekonomik olarak uzun süreli planlarla bölgedeki toplumlardan endüstrideki sorumlulara kadar bütün pay sahiplerine sosyo-ekonomik olarak yararlı olmalı. Türkiye Turizm Tanıtma ve Geliştirme Ajansı (TGA) Sürdürülebilir Turizm Endüstri Kriterleri (TR-I) başlıca konaklama yerleri ve tur operatörleri olmak üzere Türkiye turizm sektörünün sürdürülebilir gelişiminin temin edilmesi adına oluşturulmuştur.  Türkiye UNWTO Dünya Turizm Barometresine göre diğer dünya ülkelerinin aksine 2022’de turizm gelirini pandemi öncesi seviyelerin dahi üzerine çıkardı. Endüstride ekonomik olarak bu kadar belirgin bir pandemi sonrası toparlanma söz konusu iken Türkiye pandemi sonrasında daha sürdürülebilir bir gelişme için turizmde nasıl politikalar izleyebilir?"},
    {name: "Spor", guide: "https://drive.google.com/file/d/1cj7C2d4oQHr8bZp2a1GJ3tbkOUw3qdHF/view?usp=sharing", description: "2032 Avrupa Futbol Şampiyonası Finalleri (EURO 2032), dört yılda bir düzenlenen Avrupa Futbol Şampiyonası'nın 19.su olarak organize edilecek olan uluslararası futbol turnuvasıdır. 10 Ekim 2023'te UEFA tarafından yapılan açıklama ile İtalya ve Türkiye ev sahibi ülkeler olarak duyurulmuştur. Bunun ülkemizde ilk defa büyük çapta düzenlenecek bir futbol organizasyonu olmasının önemi göz önunde bulundurularak Türkiye'nin Avrupa Futbol Şampiyonası Finalleri sürecine uygun bir şekilde hazırlanabilmesi icin ne gibi adımlar atılabilir?"},
    {name: "İnönü Kabinesi", description: "Kuruluşundan itibaren küresel ve ulusal sorunlardan kurtulamamış kurtulamamış genç Türkiye Cumhuriyeti'nin kapısına, şimdiye kadar karşılaşmadığı büyüklükte bir kriz dayanmıştır. \"Büyük Savaş\" kapıdadır. Mustafa Kemal Atatürk'ün ölümünden sonra henüz yeni cumhurbaşkanı olan İsmet İnönü, en büyük kriziyle karşı karşıyadır. Daha inşa aşamasında olan genç cumhuriyetin geleceğini garanti altına almak, İsmet İnönü ve kabinesinin kaçınılmaz görevi haline gelmiştir."},
    {name: "1. Dünya Savaşı", description: "Avrupa'daki halkların ulusalcılık anlayışı sonucu yükselen ulus devletler Dünya siyasetinde askeri ve politik dominasyon sağlamak için; kolonileşme, sanayileşme, askeri teknoloji ve bilim alanlarında ufku gözükmeyen bir rekabet içine girdiler. Bu rekabet özellikle siyasi birliğini daha geç sağlamış Alman İmparatorluğu'nun Britanya'nın global hegemonyasını kendi üzerine almak istemesiyle adeta bir yarışa döndü. Bu yarış devletlerin menfaatlerini korumak için kutuplaşmaları, bloklara bölünmeleriyle sonuçlandı. Bu bloklaşmalar 20. Yüzyılın ilk çeyreğinde Avrupa'da tutuşması muhtemel bir kıvılcımın tüm dünyaya sıçramasını kaçınılmaz kılmıştı. Modernleşmiş ordular, reforme edilmiş militer doktrinler ve yenilenmiş kurmay kadroları uzun yıllar sürecek bu yangına körük olacaktı. Dünyayı yakacak bu yangını başlatmaya gereken kıvılcım için ise Saraybosna'da ateşlenecek bir kurşun yeterli gelecekti."},
]

export const metadata: Metadata = {
    title: "Komitelerimiz | İAL Gençlik Çalıştayı",
    description: "Güncel ve yaratıcı konuları ele alan komitelerimize bir göz atın."
}

export default function CommitteesPage() {
    return (
        <section className="min-h-[max(100dvh,860px)] w-full">
            <div className="fixed min-h-screen w-full">
                <Image fill src={Banner} alt="banner" className="object-cover blur-[10px] z-20" />
                <div className="absolute min-h-[max(100dvh,860px)] w-full bg-[rgba(255,255,255,.6)] z-30"></div>
            </div>
            <div className="relative flex flex-col justify-center z-40 max-w-screen-2xl min-h-[max(100dvh,860px)] mx-auto pt-32 pb-32 px-3 sm:pt-0 sm:pb-2 xsm:px-10">
                <h2 className="text-[#750000] font-bold text-[clamp(28px,3dvw,40px)] mb-10">Komitelerimiz</h2>
                <div className="grid grid-cols-2 gap-7 sm:gap-10 [&>div]:col-span-2 sm:[&>div]:col-span-1">
                    {committees.map(committee => (
                        committee.guide ? <CommitteeGuide key={committee.name} name={committee.name} description={committee.description} guide={committee.guide} /> : <Committee key={committee.name} name={committee.name} description={committee.description} />
                    ))}
                </div>
            </div>
        </section>
    )
}